name: setup-node
description: set up node environment

inputs:
  working-directory:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
        cache: yarn
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
      working-directory: ${{ inputs.working-directory }}
