name: validate-contracts

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    paths:
      - '.github/workflows/validate-contracts.yml'
      - '.github/actions/setup/node/action.yml'
      - 'contracts/**'
      - '!contracts/README.md'

env:
  target-directory: ./contracts

defaults:
  run:
    shell: bash
    working-directory: ./contracts

jobs:
  check:
    runs-on: ubuntu-latest
    concurrency: check-contracts
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/node
        with:
          working-directory: ${{ env.target-directory }}
      - name: Compile
        run: yarn compile
      - name: Lint
        run: yarn lint
      - name: Format
        run: yarn prettify

  test:
    runs-on: ubuntu-latest
    concurrency: test-contracts
    timeout-minutes: 10
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/node
        with:
          working-directory: ${{ env.target-directory }}
      - name: Run Tests
        run: yarn test
